version: "3"
services:
  nginx:
    ports:
      - "4000:80"

  node-app:
    build: .
    env_file: ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - elasticsearch
    command: npm run dev

  elasticsearch:
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
