version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
  node-app:
    build: .
    env_file: ./.env
    depends_on:
      - elasticsearch
    command: npm run start
